apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: juicy-shop
  name: juicy-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juicy-shop
  strategy:
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: juicy-shop
    spec:
      containers:
        - name: juicy-shop
          image: bkimminich/juice-shop
          imagePullPolicy: IfNotPresent
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: juicy-shop
  name: juicy-shop
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 3000
  selector:
    app: juicy-shop
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: juicy-shop-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /1
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: juicy-shop
                port:
                  number: 8080
